nycsports/config/routes.rb
Nycsports::Application.routes.draw do

	resources :users, :teams, :feeds
  root :to => 'home#index'
  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

nycsports/app/models/feed.rb
# == Schema Information
#
# Table name: feeds
#
#  id         :integer          not null, primary key
#  feed_url   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string(255)
#  team_id    :integer
#

class Feed < ActiveRecord::Base
  attr_accessible :feed_url, :name, :team_id

  belongs_to :team
end

nycsports/app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id            :integer          not null, primary key
#  icon_url      :string(255)
#  official_link :string(255)
#  twitter_link  :string(255)
#  facebook_link :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  name          :string(255)
#

class Team < ActiveRecord::Base
  attr_accessible :facebook_link, :icon_url, :name, :official_link, :twitter_link, :users, :feeds

  has_and_belongs_to_many :users
  has_many :feeds
end

nycsports/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string(255)
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :team_ids, :password, :email

  has_and_belongs_to_many :teams

  has_secure_password
end

nycsports/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
  	if session[:user_id]
  		User.find(session[:user_id])
  	end
  end
end

nycsports/app/controllers/feeds_controller.rb
class FeedsController <ApplicationController

	def index
		@feeds = Feed.all
	end

	def create
		feed = Feed.new(params['feed'])
		if feed.save!
			redirect_to feeds_path
		else
			redirect_to new_feed_path
		end
	end

	def new
		@feed = Feed.new
	end

	def edit
		@feed = Feed.find(params[:id])
	end

	def show
		@feed = Feed.find(params[:id])
	end

	def update
		feed = Feed.find(params[:id])
		feed.update_attributes(params['feed'])
		redirect_to feeds_path
	end

	def destroy
		Feed.find(params[:id]).delete
		redirect_to feeds_path
	end

end

nycsports/app/controllers/home_controller.rb
class HomeController <ApplicationController
	def index
	end
end

nycsports/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

def create
  user = User.find_by_email(params[:email])
  #puts 'located user: ' + user.name
  authenticated_user = user.authenticate(params[:password])
  if authenticated_user
    session[:user_id] = authenticated_user.id
    message = 'You are authenticated!'
    render text: message, layout: true
  else
    redirect_to sessions_new_path
  end
end

def destroy
  session[:user_id] = nil
  current_user_id = nil
  redirect_to sessions_new_path
end

end

nycsports/app/controllers/teams_controller.rb
class TeamsController <ApplicationController

	def index
		@teams = Team.all
	end

	def create
		team = Team.new(params['team'])
		if team.save!
			redirect_to teams_path
		else
			redirect_to new_team_path
		end
	end

	def new
		@team = Team.new
		@feeds = Feed.all
	end

	def edit
		@team = Team.find(params[:id])
		@feeds = Feed.all
	end

	def show
		@team = Team.find(params[:id])
		@feeds = Feed.all
	end

	def update
		team = Team.find(params[:id])
		team.update_attributes(params['team'])
		redirect_to teams_path
	end

	def destroy
		Team.find(params[:id]).delete
		redirect_to teams_path
	end

end

nycsports/app/controllers/users_controller.rb
class UsersController <ApplicationController

	def index
		@users = User.all
	end

	def create
		user = User.new(params['user'])
		if user.save!
			redirect_to root_path
		else
			redirect_to new_user_path
		end
	end

	def new
		@user = User.new
		@teams = Team.all
		#@session = Session.new
	end

	def edit
		@user = User.find(params[:id])
		@teams = Team.all
	end

	def show
		@user = User.find(params[:id])
		@teams = Team.all
		#@feeds = Feed.all
	end

	def update
		user = User.find(params[:id])
		user.update_attributes(params['user'])
		redirect_to users_path
	end

	def destroy
		User.find(params[:id]).delete
		redirect_to users_path
	end

end

nycsports/app/helpers/application_helper.rb
module ApplicationHelper
end

nycsports/app/views/feeds/edit.html.erb
<h2>Edit Feed</h2>
<%= render partial: 'feeds/partials/form' %>

nycsports/app/views/feeds/index.html.erb
<h1>Index Feeds Page </h1>
<h3>ADMIN ONLY</h3>

<ul>
	<% @feeds.each do |feed| %>
		<li>
	 		<p><%= link_to "#{feed['name']}", feed_path(feed) %></p>
	 		<%= link_to 'Edit Feed', edit_feed_path(feed) %>
	 		<%= link_to "Delete Feed", feed_path(feed), method: :delete %>
		 	<br/> <br/>
		</li>
	<% end %>
</ul>

nycsports/app/views/feeds/new.html.erb
<h2>New Feed</h2>
<%= render partial: 'feeds/partials/form' %>

nycsports/app/views/feeds/partials/_form.html.erb
<%= form_for @feed do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :feed_url %>
	<%= f.text_field :feed_url %>

	<%= f.submit %>
<% end %>

nycsports/app/views/feeds/show.html.erb
<h1>Show Feed Page!</h1>

nycsports/app/views/home/index.html.erb
Index Home Successful

nycsports/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NYCSports</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if current_user %>
	<%= current_user.name %>
	<%= link_to 'logout', logout_path, method: :delete %> <br>
<% end %>
<%= render partial: 'layouts/partials/nav' %>

<%= yield %>

</body>
</html>

nycsports/app/views/layouts/partials/_nav.html.erb
<ul class="side-nav">
	<li class="active"><%= link_to 'Home', root_path %></li>
	<li class="divider"></li>
	<li><%= link_to 'Users', users_path %></li>
	<li class="divider"></li>
	<li><%= link_to 'Teams', teams_path %></li>
	<li class="divider"></li>
	<li><%= link_to 'Feeds', feeds_path %></li>
	<li class="divider"></li>
	<li><%= link_to 'New User', new_user_path %></li>
	<li class="divider"></li>
	<li><%= link_to 'New Team', new_team_path %></li>
	<li class="divider"></li>
	<li><%= link_to 'New Feed', new_feed_path %></li>
</ul>

nycsports/app/views/users/edit.html.erb
<h2>Edit User Page</h2>
<%= render partial: 'users/partials/form' %>

nycsports/app/views/users/index.html.erb
<h1>User Index Page</h1>
<h3>ADMIN ONLY</h3>

<ul>
	<% @users.each do |user| %>
		<li>
			<p><%= link_to "#{user['name']}", user_path(user)%></p>
			<%= link_to 'Edit User Profile', edit_user_path(user) %>
			<%= link_to 'Delete User', user_path(user), method: :delete %> 
			<br/> <br/>
		</li>
	<% end %>
</ul>

nycsports/app/views/users/new.html.erb
<h2>Create Your User Profile</h2>
<%= render partial: 'users/partials/form' %>

nycsports/app/views/users/partials/_form.html.erb
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %> <br/>

	<%= f.label :email %>
	<%= f.email_field :email %> <br/>

	<%= f.label :password %>
	<%= f.password_field :password %> <br/>

	<p>Which teams would you like to follow?</p>
	<% @teams.each do |team| %>
		<span> <%= team.name %> </span>
		<%= check_box_tag "user[team_ids][]", team.id, team.in?(@user.teams.to_a) %>
	<% end %>

	<%= f.submit %>
<% end %>

nycsports/app/views/users/show.html.erb
<p><%="#{@user.name}"%>'s Feeds: </p>
<p>
	<ul>
		<% @user.teams.each do |team| %>
			<% team.feeds.each do |feed| %>
				<li>
					<%= link_to "#{feed['name']}", feed_path(feed) %>
				</li>
			<% end %>
		<% end %>
	</ul>
</p>